version: "3.7"
services:
  app:
    image: ${DOCKER_REGISTRY}/demo:latest
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:80" # map 80 in container => 3000 in local
    restart: unless-stopped

