version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY}/apigateway
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY}/catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  patient.api:
    image: ${DOCKER_REGISTRY}/patientapi
    build:
      context: .
      dockerfile: Services/Patient/Patient.API/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY}/identityserver
    build:
      context: .
      dockerfile: IdentityServer/IdentityServer/Dockerfile

  user.api:
    image: ${DOCKER_REGISTRY}/userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile
  
  lisdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    
  minio:
    image: minio/minio

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.5.3

  # jenkins:
  #   image: jenkins/jenkins:lts

  kong-database:
    image: postgres:11

  kong-migrations:
    image: kong:3.4

  kong-node-1:
    image: kong:3.4

  kong-node-2:
    image: kong:3.4

  prometheus:
    image: prom/prometheus

  grafana:
    image: grafana/grafana
    


 



