version: '2.4'

services:

  authorize.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=Host=103.82.25.49;Port=6000;Database=authorize;Username=kendz;Password=kienteo1012"
      - KEYCLOAK_URL=https://103.82.25.49:8443
      - KEYCLOAK_REALM=Demo
      - Keycloak__ClientId=admin-cli
      - Keycloak__ClientSecret=test
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - EmailSettings__ApiKey
      - EmailSettings__FromAddress=kienteo1012@gmail.com
      - EmailSettings__FromName=KenVerse
    ports:
      - "8083:80"
    restart: unless-stopped

  account.api:
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=Host=103.82.25.49;Port=6000;Database=account;Username=kendz;Password=kienteo1012"
      - "MINIO_CONNECTION=103.82.25.49;9000;kendz;kienteo1012"
      - KEYCLOAK_URL=https://103.82.25.49:8443
      - KEYCLOAK_REALM=Demo
      - Keycloak__ClientId=admin-cli
      - Keycloak__ClientSecret=test
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - Redis_Host=redis
    ports:
      - "8082:80"
    restart: unless-stopped
    
  
  minio:
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: kendz
      MINIO_ROOT_PASSWORD: kienteo1012
    command: server --console-address ":9001" /data
    restart: always

#  kong-database:
#    container_name: kong-database
#    restart: always
#    environment:
#      POSTGRES_USER: kong
#      POSTGRES_DB: kong
#      POSTGRES_PASSWORD: kong
#    volumes:
#      - kong-database-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    mem_limit: 1g
#    cpus: 0.5
#    command: >
#      postgres
#      -c shared_buffers=256MB
#      -c work_mem=2MB
#      -c effective_cache_size=512MB

#  kong-migrations:
#    container_name: kong-migrations
#    depends_on:
#      - kong-database
#    environment:
#      KONG_DATABASE: postgres
#      KONG_PG_HOST: kong-database
#      KONG_PG_USER: kong
#      KONG_PG_PASSWORD: kong
#    command: kong migrations bootstrap
#    restart: on-failure

#  kong-node-1:
#    container_name: kong-node-1
#    depends_on:
#      - kong-database
#      - kong-migrations
#    ports:
#      - "8000:8000"  # Proxy
#      - "8001:8001"  # Admin API
#      - "8002:8002"  # Kong Manager
#    environment:
#      KONG_DATABASE: postgres
#      KONG_PG_HOST: kong-database
#      KONG_PG_USER: kong
#      KONG_PG_PASSWORD: kong
#      KONG_ADMIN_LISTEN: 0.0.0.0:8001
#      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
#      KONG_PROXY_ACCESS_LOG: /dev/stdout
#      KONG_ADMIN_ACCESS_LOG: /dev/stdout
#      KONG_PROXY_ERROR_LOG: /dev/stderr
#      KONG_ADMIN_ERROR_LOG: /dev/stderr
#      KONG_DB_CACHE_TTL: 3600
#    restart: always
   
#  kong-node-2:
#    container_name: kong-node-2
#    depends_on:
#      - kong-database
#      - kong-migrations
#    ports:
#      - "8005:8005"  # Proxy
#      - "8006:8006"  # Admin API
#      - "8007:8007"  # Kong Manager
#    environment:
#      KONG_DATABASE: postgres
#      KONG_PG_HOST: kong-database
#      KONG_PG_USER: kong
#      KONG_PG_PASSWORD: kong
#      KONG_PROXY_LISTEN: 0.0.0.0:8005
#      KONG_ADMIN_LISTEN: 0.0.0.0:8006
#      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8007
#      KONG_PROXY_ACCESS_LOG: /dev/stdout
#      KONG_ADMIN_ACCESS_LOG: /dev/stdout
#      KONG_PROXY_ERROR_LOG: /dev/stderr
#      KONG_ADMIN_ERROR_LOG: /dev/stderr
#      KONG_DB_CACHE_TTL: 3600
#    restart: always

  # prometheus:
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"

  presence:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis_Host=redis
    ports:
      - "5080:80"
    depends_on:
      - redis

  channel.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=Host=103.82.25.49;Port=6000;Database=channel;Username=kendz;Password=kienteo1012"
      - "MINIO_CONNECTION=103.82.25.49;9000;kendz;kienteo1012"
    ports:
      - "8081:80"

  redis:
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]

  account.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SQL_CONNECTION=Host=103.82.25.49;Port=6000;Database=account;Username=kendz;Password=kienteo1012"
    ports:
      - "8011:80"

  directmessage.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

volumes:
#  elasticsearch_data:
#    driver: local  
##  jenkins_home:
#  kong-database-data:
  redis_data:
#  portainer_data:
#  postgres_data:

networks:
  elk:
    driver: bridge
  backend:
    driver: bridge






