version: '3.4'

services:
  authorize.api:
    image: ${DOCKER_REGISTRY}/authorizeapi
    build:
      context: .
      dockerfile: Authorize/Authorize/Dockerfile

  account.api:
    image: ${DOCKER_REGISTRY}/accountapi
    build:
      context: .
      dockerfile: Services/Account/Account.API/Dockerfile

  minio:
    image: minio/minio

  pg-database:
    image: postgres:11

  kong-migrations:
    image: kong:3.4

  kong-node-1:
    image: kong:3.4
  
#  zookeeper:
#    image: wurstmeister/zookeeper:3.4.6

  channel.api:
    image: ${DOCKER_REGISTRY}/channelapi
    build:
      context: .
      dockerfile: Services/Channel/Channel.API/Dockerfile

  guild.api:
    image: ${DOCKER_REGISTRY}/guildapi
    build:
      context: .
      dockerfile: Services/Guild/Guild.API/Dockerfile

  notification.api:
    image: ${DOCKER_REGISTRY}/notificationapi
    build:
      context: .
      dockerfile: Services/Notification/Notification.API/Dockerfile
  
  media.api:
    image: ${DOCKER_REGISTRY}/mediaapi
    build:
      context: .
      dockerfile: Services/Media/Media.API/Dockerfile
  
  redis:
    image: redis:7

#
#  directmessage.api:
#    image: ${DOCKER_REGISTRY-}/directmessageapi
#    build:
#      context: .
#      dockerfile: Services/DirectMessage/DirectMessage.API/Dockerfile


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.18

