version: '3.4'

services:
  authorize.api:
    image: ${DOCKER_REGISTRY}/authorizeapi
    build:
      context: .
      dockerfile: Authorize/Authorize/Dockerfile

  account.api:
    image: ${DOCKER_REGISTRY}/accountapi
    build:
      context: .
      dockerfile: Services/Account/Account.API/Dockerfile
  
#  kenverse-postgreSQL:
#    image: postgres:15
    
  minio:
    image: minio/minio

#  kong-database:
#    image: postgres:11
#
#  kong-migrations:
#    image: kong:3.4
#
#  kong-node-1:
#    image: kong:3.4
#
#  kong-node-2:
#    image: kong:3.4
    
  presence:
    image: ${DOCKER_REGISTRY}/presence
    build:
      context: .
      dockerfile: Services/Presence/Presence/Dockerfile
  
#  zookeeper:
#    image: wurstmeister/zookeeper:3.4.6

  channel.api:
    image: ${DOCKER_REGISTRY}/channelapi
    build:
      context: .
      dockerfile: Services/Channel/Channel.API/Dockerfile

  redis:
    image: redis:7

  account.grpc:
    image: ${DOCKER_REGISTRY-}/accountgrpc
    build:
      context: .
      dockerfile: Services/Account/Account.Grpc/Dockerfile

