version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "9874:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    restart: unless-stopped

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=Server=lisdb;Database=Catalog;User Id=sa;Password=Kienteo1012;TrustServerCertificate=True"
    ports:
      - "80"
    restart: unless-stopped


  patient.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=Server=lisdb;Database=Patient;User Id=sa;Password=Kienteo1012;TrustServerCertificate=True"
    ports:
      - "80"
    restart: unless-stopped


  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    restart: unless-stopped

  lisdb:
    user: root
    container_name: lisdb
    environment:
      - SA_PASSWORD=Kienteo1012
      - ACCEPT_EULA=Y
    restart: always
    ports: 
      - "1433:1433"
    volumes:
      - lisdb-data:/var/opt/mssql/data

  minio:
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: kendz
      MINIO_ROOT_PASSWORD: kienteo1012
    command: server --console-address ":9001" /data
    restart: always
   
  elasticsearch:
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true  # Disable security for local setup
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Set memory limits
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
   
  kibana:
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
    ports:
      - "5601:5601"

volumes:
  lisdb-data:  
  elasticsearch_data:
    driver: local  