global:
  scrape_interval: 15s

scrape_configs:
  - job_name: kong
    metrics_path: /metrics
    static_configs:
      - targets: ['kendz.site:8001']
        labels:
          instance: kong1
      - targets: ['kendz.site:8006']
        labels:
          instance: kong2
