<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Exception\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Confluent.Kafka" Version="2.10.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="Google.Protobuf" Version="3.31.1" />
    <PackageReference Include="Grpc.AspNetCore.Server" Version="2.71.0" />
    <PackageReference Include="Grpc.AspNetCore.Server.ClientFactory" Version="2.71.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.71.0" />
    <PackageReference Include="Grpc.Net.Common" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MediatR" Version="11.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Library\Service.Lib\Service.Lib.csproj" />
    <ProjectReference Include="..\Channel.Domain\Channel.Domain.csproj" />
  </ItemGroup>

	<ItemGroup>
	  <Protobuf Include="Protos\User.proto" GrpcServices="Client" />
	</ItemGroup>
</Project>
