syntax = "proto3";

option csharp_namespace = "Account.Grpc.Protos";

service AccountProtoSerivce{
	rpc GetUserByUserNameOrEmail(GetUserByUserNameOrEmailRequest) returns (UserModel);
	rpc GetUserInfoInChannel(GetUserInfoInChannelRequest) returns (GetUsersInfoInChannelResponse);
	rpc GetListFriend(GetListFriendRequest) returns (GetListFriendResponse);
}

message GetUserByUserNameOrEmailRequest {
	string search = 1;
}

message GetUserInfoInChannelRequest {
	repeated string userId = 1;
}

message GetUsersInfoInChannelResponse {
	repeated UserModel users = 1;
}

message GetListFriendRequest {
	string userId = 1;
}

message GetListFriendResponse {
	repeated UserRelationshipModel friends = 1;
}

message UserModel{
	string id = 1;
	string userName = 2;
	string email = 3;
	string displayName = 4;
	string status = 5;
	string avatarUrl = 6;
}
message UserRelationshipModel {
	string id = 1;
	string userName = 2;
}
