<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="FluentValidation" Version="11.11.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
		<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
		<PackageReference Include="Minio" Version="6.0.4" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.51.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Exception\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Library\Service.Lib\Service.Lib.csproj" />
	  <ProjectReference Include="..\Authorize.Domain\Authorize.Domain.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Protobuf Include="..\..\Services\Account\Account.Grpc\Protos\User.proto" GrpcServices="Client">
			<Link>Protos\User.proto</Link>
		</Protobuf>
	</ItemGroup>

</Project>