server {    

    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri /index.html =404;
    }

    location /api-gw/ {
        rewrite ^/api-gw/(.*)$ /$1 break;
        proxy_pass http://103.82.25.49:9874;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /kong-gw/ {
        rewrite ^/kong-gw/(.*)$ /$1 break;
        proxy_pass http://kong_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /minio/ {
        proxy_pass http://103.82.25.49:9000/; # Replace with MinIO's host and port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Rewrite to ensure proper asset loading
        rewrite ^/minio/(.*)$ /$1 break;

        proxy_redirect off;

        # Optional: Increase body size for uploads
        client_max_body_size 100M;

        # Optional: WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    error_page 500 502 503 504 /50x.html;   
}

upstream kong_upstream {
    round_robin;
    server 103.82.25.49:8000 max_fails=3 fail_timeout=30s;
    server 103.82.25.49:8005 max_fails=3 fail_timeout=30s;

    health_check interval=5 fails=3 passes=2 timeout=1;
}
