# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend

on:
  push:
    branches: ["main"]

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Login container docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build:
    runs-on: ubuntu-latest
    needs: docker-login
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build image
        run: |
          export DOCKER_REGISTRY=${{ secrets.DOCKER_USER }}/
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          cd demo-frontend
          docker compose build
          docker compose push

      - name: "Upload Docker compose"
        uses: actions/upload-artifact@v4
        with:
          name: key-docker-compose
          path: |
            demo-frontend/docker-compose.yml
          retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download docker-compose
        uses: actions/download-artifact@v4
        with:
          name: key-docker-compose

      - name: Check dictionary
        run: ls -a

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_DEPLOY_IP }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SSH_DEPLOY_USER }}
          password: ${{ secrets.SSH_DEPLOY_PASSWORD }}
          source: "docker-compose.yml"
          target: "app/demo-frontend"

      - name: Connection SSH - build server docker compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_DEPLOY_IP }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SSH_DEPLOY_USER }}
          password: ${{ secrets.SSH_DEPLOY_PASSWORD }}
          script: |
            cd app/demo-frontend
            sed -i '/build:\|context:\|dockerfile:/d' docker-compose.yml
            docker-compose down
            docker-compose pull
            docker-compose up -d --build
